### ISSUE TITLE
Pasting from google docs/MS Word

### ISSUE THREAD

**Issue by michaelryancaputo** [nhnent/tui.editor#118] opened 2018-03-16 16:23 UTC
## Version
1.0.4

## Test Environment
Chrome (latest), Mac OSX (latest)

## Current Behavior
When copying from a google docs containing formatting, the pasted content into TUI-Editor contains a lot of unnecessary markup. This normally would not be an issue, but it seems to cause issues when applying opening/closing `p` and `br` tags.

This is an example of the outputted HTML
```html
<p><span class="colour" style="color:rgb(0, 0, 0)"><strong>Owner</strong>: The owner of this thing</span><br>
<span class="colour" style="color:rgb(0, 0, 0)"><strong>Update frequency</strong>: anotherformatted line</span>&nbsp;<span class="colour" style="color:rgb(0, 0, 0)"></span><br>
<span class="colour" style="color:rgb(0, 0, 0)"><strong>Goal</strong>: Capture some information about the thing.</span><br data-tomark-pass=""><br>
<br data-tomark-pass=""></p>
```

## Expected Behavior
The span tags seem harmless, but it seems like it's inserting `br` tags that are not self closing.

**Comment by kyuwoo-choi** [comment] 2018-03-30 01:48
@michaelryancaputo  thanks for reporting it.

normally `<p>` shouldn't be in WYSIWYG editor.  we keep a line as a `<div>`.
I guess somehow the `<p>` leaked in.

could you give me **an example of the google docs**, so I can reproduce and track the problem?

**Comment by michaelryancaputo** [comment] 2018-03-30 01:54
@kyuwoo-choi Here's a link: https://docs.google.com/document/d/1vD6rdcVYqEH9HS3rgPHEkCpZzxlJ-kjiRSRqdHlHutE/edit?usp=sharing

**Comment by kyuwoo-choi** [comment] 2018-03-30 02:49
@michaelryancaputo LOL. so fast.

I've tested given google docs and find no `<p>` in WYSIWYG editor.
It might be because of your chrome extension.
Could you confirm?

btw. Thank you for your steady contributions 👍

**Comment by michaelryancaputo** [comment] 2018-05-02 15:46
It seems like it might also be a problem with microsoft word

**Comment by sohee-lee7** [comment] 2019-02-21 08:28
@michaelryancaputo Sorry for late reply. We manage this issue in #401 so close it.

**Closed by sohee-lee7** 2019-02-21 08:28 UTC
Labels: Category: Clipboard, Type: Bug
