### ISSUE TITLE
How can I remove base64 content when I upload image?

### ISSUE THREAD

**Issue by horan-geeker** [nhnent/tui.editor#127] opened 2018-04-04 02:41 UTC
First, thanks for your job!

## Version

1.0.5
## Test Environment

Mac Chrome
## Current Behavior

I have use addImageBlobHook callback to upload image, but Base64 also insert into textarea
```js
addImageBlobHook: function (blob, callback) {
                            var uploadedImageURL = that.imageUpload(blob);
                            callback(uploadedImageURL, 'alt text');
                            return false;
                        }
```
content like this, appear twice
```
![alt text](image url)![ie.png](data:image/png;base64,iVBORw0KGgoAA......
```
## Expected Behavior

only my code here
```
![alt text](image url)
```
so, how can I remove base64 code when I upload a image?

**Comment by kyuwoo-choi** [comment] 2018-04-05 01:17
oh well.
The code snippet you wrote should work fine.
the base64 image string should be replaced with uploaded URL.

I have tested it now and I can't reproduce.
will you post your example on codepen or somewhere?

**Comment by horan-geeker** [comment] 2018-04-05 14:41
Sorry to tell that I can't upload `tui-editor.js` and other files on **codeopen**, so I post them on my own server where you can see the source code from the follow page.

this is my server address [http://115.28.82.133/example00-demo.html](http://115.28.82.133/example00-demo.html) you can drop a file into content block and do a test. the truth is that it appeared twice, I don't know if I use it in a wrong case.

I have downloaded project zip file, there are three file in  `dist/` directory `tui-editor-Editor-all.js`, `tui-editor.css` and `tui-editor-contents.css` I have include them in my demo,  as for other js and css files I copied urls from your example page `example00-demo.html`

**Comment by toby1991** [comment] 2018-04-08 03:16
![image](https://user-images.githubusercontent.com/5897356/38462693-eb5a6846-3b1d-11e8-9f76-caa1dcf59818.png)

# @horan-geeker  You wrote the `addImageBlobHook` in the `events`, but it is a `hooks`, dude.

![image](https://user-images.githubusercontent.com/5897356/38462706-25828cc4-3b1e-11e8-87f6-b34b5110f544.png)


@kyuwoo-choi  This issue should be closed.

**Comment by horan-geeker** [comment] 2018-04-08 03:24
Sorry, It's my fault, thank u @toby1991

**Comment by kyuwoo-choi** [comment] 2018-04-10 06:10
I think we can close this issue.

**Closed by kyuwoo-choi** 2018-04-10 06:10 UTC
Labels: question

**Comment by wangchongchong1007** [comment] 2018-05-22 07:39
@horan-geeker hi, I found if I remove the base64 content the preview of the picture will disappear. So how should I replace the base64 code?

**Comment by horan-geeker** [comment] 2018-05-22 07:46
@wangchongchong1007 you need use addImageBlobHook in hooks section, and the page will only has  a href without any base64 code.

**Comment by 2klm** [comment] 2021-06-30 08:05
@horan-geeker I know it's been 3 years, but can you share your upload script if you still have it please ? It would really help me
I can't seem to manage upload and the blob variable returns metadata and not an actual image file

**Comment by 2klm** [comment] 2021-07-01 07:43
@toby1991 I'm running into the same problem, although I did write my code in hooks and not in events

**Comment by 2klm** [comment] 2021-07-01 08:20
@kyuwoo-choi I'm running into the same problem, although I did write my code in hooks and not in events
Here is my code snippet : 

```
hooks: { 
        addImageBlobHook: function (blob, callback) {

            let image = new FormData();

            image.append(0, blob, blob.name);

            fetch('upload.php', {
                method: 'POST',
                body: image
            }).then(function (response) {
                if (response.ok) {
                    response.json().then((value) => { 
                        if (value === 0) { 
                            alert("file upload error");
                        } else { 
                            callback(value, 'uploaded image'); 
                        }
                    });
                } else { 
                    alert("file upload error");
                }
            })
            return false; // I tried with true, and without return at all, same result
        }
    }
```

**Comment by js87zz** [comment] 2021-07-01 08:30
@2klm 
Please open a new issue instead of asking questions about the closed issue. The maintainer(`kyuwoo-choi`) is no longer involved in this project.
